### ISSUE TITLE
Problem about played courses

### ISSUE THREAD

**Issue by lilystudent2016** [SmmServer/SmmServer#11]
When I open a new save, the played courses data  will be displayed normally in course world.Then I download a perfect save to replace my new save, the played courses data in course world is disappeared.I try to open another new save and  the played courses data will return.Is this a BUG?

**Comment by ums-i** [comment]
what version of smmserver do you have?

**Comment by mrexodia** [comment]
I believe your save contains the played courses, but if you could attach that perfect safe it would be appreciated.

**Comment by lilystudent2016** [comment]
> I believe your save contains the played courses, but if you could attach that perfect safe it would be appreciated.

I download the perfect save here:
https://gbatemp.net/threads/wii-u-save-files-compilation.427761
 000500001018dc00.zip
"US Super Mario Maker (000500001018DC00) save:
-All items unlocked in Create mode.
-All Mystery Mushroom customs obtained (153/153).
-All official courses finished."
https://drive.google.com/open?id=1apVzmC8hKgNWziSMetp7vKt0R1RAnvat

Thank you!

**Comment by mrexodia** [comment]
It's likely not a bug @lilystudent2016. The save contains your played courses (it's weirdly cached), so likely you'll just lose them (since the official courses do not exist)

**Comment by mrexodia** [comment]
Nope, Super Mario Maker 2 is an actively supported Nintendo product on an
activity supported console and I’m not interested in working on it.

That being said, the source code of SmmServer is available and since it
looks like NintendoClients on which the server code is based supports the
Switch it’s not impossible to implement.

**Comment by lilystudent2016** [comment]
All right, thank you for your nice work!
