### ISSUE TITLE
Game Crashing When Selecting "Course World"

### ISSUE THREAD

**Issue by COBLoneWolf** [SmmServer/SmmServer#17]
[Caddy.log](https://github.com/SmmServer/SmmServer/files/4699235/Caddy.log)
[Debug.log](https://github.com/SmmServer/SmmServer/files/4699236/Debug.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/4699237/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/4699238/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/4699239/Pretendo%2B%2B.log)

I attached my debug files. I updated CEMU and SMM to 272 and every time I select "Course World" form the main menu, the game crashes and I have no idea why.  I tried everything in my power to fix it, but no solution it would awesome around here can help, thanks

**Comment by mrexodia** [comment]
Connection-wise everything seems fine, so likely it's just Cemu crashing. You can try updating Cemu to the latest version, just copy the new Cemu into SmmServer's Cemu directory (since you need a bunch of files)

**Comment by COBLoneWolf** [comment]
I even started off fresh and new to make sure I wasn't doing anything wrong. Meaning I download SMM, extracted the files, updated the CEMU inside the SMMServer folder to version 1.19, updated Super Mario Marker to version 272, clicked on "Course World", and it crashed on me again. Im just about to give up and wait for SMMSever to update unless anyone else has any other ideas

**Comment by mrexodia** [comment]
The game is crashing, SmmServer is working fine. Try using your legitimate
online account and see if everything works correctly there.

**Comment by COBLoneWolf** [comment]
Here's the thing I dont have a Nintendo Online Account,  Are you pretty much out of ideas?

**Comment by COBLoneWolf** [comment]
Since its CEMU issue and not a SMMServer issue Im going to close this
