### ISSUE TITLE
Cemu ErrEula Error Code 102-1020

### ISSUE THREAD

**Issue by sheeta1998** [SmmServer/SmmServer#19]
I'm having a problem 
I'm playing Hyrule Warriors with all the graphics packs enabled. the Game runs fine until I've beaten a level where I see this Error Code Message and it won't let me continue. I've searched for an answer and haven't found one can someone help???
![tjiedtj](https://user-images.githubusercontent.com/51679497/91878307-b5c8fa00-ec44-11ea-9762-a7d2c13be046.PNG)

**Comment by mrexodia** [comment]
This is for super mario maker, not sure why you would think it works on another game...
