### ISSUE TITLE
ErrEula Error-Code: 106-0502

### ISSUE THREAD

**Issue by jpcapone** [SmmServer/SmmServer#2]
I get the listed error when I click on the main menu and then course world within super mario maker in cemu.  I have found what the error means but I don't know how to address the network connectivity of the Nintendo Client components.  I am open to any suggestion, thanks.
![smmservererror](https://user-images.githubusercontent.com/47680328/68036201-9f0bec80-fc9b-11e9-81df-bf7be3649009.JPG)

**Comment by mrexodia** [comment]
Please provide the log files that are next to SmmServer.

**Comment by jpcapone** [comment]
Please let me know if you need anything else.
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3798725/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3798726/NEX.SMM.log)

[Caddy.log](https://github.com/SmmServer/SmmServer/files/3798727/Caddy.log)

**Comment by mrexodia** [comment]
It seems you are not using the version of Cemu that comes with SmmServer.

**Comment by jpcapone** [comment]
I am 100% using the version that is bundled as you can see at the bottom of the screenshot.  I also see (smmdb) next to Cemu 1.15.17c when I launch Cemu from the SmmServer instance. I did have a previous version installed though.  Could there be some configuration files somewhere that the bundled version is using?
![smmserverror2](https://user-images.githubusercontent.com/47680328/68042664-d08bb480-fca9-11e9-87de-8f2cfe6ddac7.JPG)
.  I did have a previous version installed though.

**Comment by mrexodia** [comment]
If you made any changes to the contents of the SmmServer archive it can cause issues.

You can try this:
- Do a fresh install of SmmServer and do not make any changes to any of the files
- Download and run [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) as Administrator
- Put in the following on the filter dialog that shows on startup:
  ![](https://i.imgur.com/wMkkW2W.png)
- In the main application use the following settings:
  ![](https://i.imgur.com/uY1AILH.png)
- Click 'Start'
- Click 'Start Cemu'
- Install the update for SMM through the Cemu menu and configure your controller etc

Use the started Cemu to start the game and try going online and then send the DebugView logs.

If that does not work you can add the following entries to `C:\Windows\system32\drivers\etc\hosts`:

```
127.0.0.1 account.nintendo.net
127.0.0.1 wup-ama.app.nintendo.net
```

**Comment by jpcapone** [comment]
How do you "Install the update for SMM through the Cemu menu"?
I wasn't aware of that being a step in the regular install process.

**Comment by mrexodia** [comment]
http://wiki.cemu.info/wiki/Tutorial:How_to_update_a_game

**Comment by jpcapone** [comment]
Ok so you mean update Super Mario Maker?  I updated it as you can see in the screenshot I provided.  I thought you meant there was an update for the SMMServer via CEMU.  I have added the entries to the host file.  I will follow the other steps and provide the logs.

**Comment by jpcapone** [comment]
[debugger.LOG](https://github.com/SmmServer/SmmServer/files/3799798/debugger.LOG)

[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3799793/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3799794/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/3799795/Pretendo%2B%2B.log)
[Caddy.log](https://github.com/SmmServer/SmmServer/files/3799796/Caddy.log)
I got further I am guessing because I had to disable a bunch of background apps to get the debug viewer working but I eventually ran into the same error.

**Comment by mrexodia** [comment]
Everything is working as expected.

```
[2019-11-01 18:17:54] INFO: detected course browser (highlights, normal)
```

As documented, the course browser is not supported. You should be able to play 100 mario without any issues from this point. You likely got `106-1202` this time, from the looks of it when trying to do something that is not implemented (from the looks of it you tried to view all courses).

**Comment by jpcapone** [comment]
Ahh got it.  How can I confirm connectivity to SMMDB?  Thanks for your help!

**Comment by mrexodia** [comment]
There is no 'connectivity' really. Whenever you play a level the SMM NEX tab will say something like:

```
[2019-10-28 00:19:30] INFO: [smmdb] fetching 1 Difficulty.Easy courses
[2019-10-28 00:19:31] INFO: [smmdb] skipping 5d5f19385553e6487f5ae368
[2019-10-28 00:19:31] INFO: [smmdb] skipping 5d1ccf0830a795d59ad0da13
[2019-10-28 00:19:31] INFO: [smmdb] skipping 5ccb796b85c1a06b0a9f3543
[2019-10-28 00:19:31] INFO: [smmdb] skipping 5cc17a45e8697b7e6e6c78c8
[2019-10-28 00:19:31] INFO: [smmdb] downloaded 5cb3d9db8b9ca781c86a3688 (index: 10000001621)
[2019-10-28 00:19:32] INFO: [smmdb] nothing to do for Difficulty.Normal
[2019-10-28 00:19:32] INFO: [smmdb] nothing to do for Difficulty.Expert
[2019-10-28 00:19:32] INFO: [smmdb] nothing to do for Difficulty.SuperExpert
```

This is to ensure there is always ~300 levels available to play.

**Comment by jpcapone** [comment]
Got it, thanks.  If anyone stumbles across this I think I had some auto start up app blocking connectivity.  It could have been one of a few apps that i uninstalled but I think it was the Cisco Open DNS client.

**Comment by RenanZX** [comment]
I have a similar problem, but i don't know what is happening, whenever i get into the game, cemu simply close before it show's the title screen

**Comment by Xevets** [comment]
I'm having this same error when trying to go to course world. I followed the above steps and it didn't resolve the error. Any suggestions?
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3802616/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3802617/NEX.SMM.log)
[Caddy.log](https://github.com/SmmServer/SmmServer/files/3802618/Caddy.log)

**Comment by RyotaSakamoto16** [comment]
el mismo problema, y nada, alguien que sepa la solución?

**Comment by mrexodia** [comment]
No logs in Pretendo++ happens because Cemu is not connecting to SmmServer @RyotaSakamoto16. Read the suggestions in the issue tracker and try those and if nothing works make a video of your desktop where you install everything from scratch and start the game.

In your case the error is:

```
2019/11/23 03:54:47 Listen: listen tcp :80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

Which indicates there is already a web server running, see https://github.com/SmmServer/SmmServer/issues/5

**Comment by wOwfmasf2** [comment]
Help me

**Comment by RaynMaster88** [comment]
same here please help me thanks a lot!
[Caddy.log](https://github.com/SmmServer/SmmServer/files/6543308/Caddy.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/6543310/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/6543311/NEX.SMM.log)

**Comment by mastergive514** [comment]
Thanks! Now i can play SMM 100 mario now
