### ISSUE TITLE
I still get an error code regardless and I don't think smm server works. I dont understand attach akk .log files as well

### ISSUE THREAD

**Issue by Dredibis** [SmmServer/SmmServer#26]
Make sure to perform the following steps:

1. Open SmmServer
2. Click 'Start' to start the server
3. After a few seconds the 'Debug' button should become visible, press it
4. Wait for a while (~30 seconds)
5. Attach all `.log` files to the issue

**Comment by mrexodia** [comment]
Please perform the steps 🙂

**Comment by Dredibis** [comment]
Do I attach the debug files or the log files?

**Comment by Dredibis** [comment]
[log.txt](https://github.com/SmmServer/SmmServer/files/5987399/log.txt)
[Caddy.log](https://github.com/SmmServer/SmmServer/files/5987400/Caddy.log)
[Debug.log](https://github.com/SmmServer/SmmServer/files/5987402/Debug.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/5987403/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/5987404/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/5987405/Pretendo%2B%2B.log)

Anyways this is all the files

**Comment by mrexodia** [comment]
If you look in `README.txt` at the `Troubleshooting steps` section you can find the ports required to be open. In your case you have to change the port VMWare uses, see https://github.com/SmmServer/SmmServer/issues/5#issuecomment-554645790 for more details.

**Comment by Dredibis** [comment]
Alright I was finally able to access the course world however I can't play online courses or play the 100 mario challenge as i got the error code 106-0103

**Comment by Dredibis** [comment]
nevermind my game wasnt updated thank you so much for your help it works now :)
