### ISSUE TITLE
106-0502 error

### ISSUE THREAD

**Issue by SpYHero33** [SmmServer/SmmServer#27]
Debug has this problem:
  Traceback (most recent call last):
    File "E:\mario\SmmServerFinal\NintendoClients\smm_example_public.py", line 50, in <module>
      backendclient.connect(nex_token_smm.host, nex_token_smm.port)
    File "E:\mario\SmmServerFinal\NintendoClients\nintendo\nex\backend.py", line 54, in connect
      raise ConnectionError("Couldn't connect to authentication server")
ConnectionError: Couldn't connect to authentication server
[Caddy.log](https://github.com/SmmServer/SmmServer/files/6261419/Caddy.log)
[Debug.log](https://github.com/SmmServer/SmmServer/files/6261420/Debug.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/6261421/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/6261422/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/6261424/Pretendo%2B%2B.log)

**Comment by sofientouati** [comment]
I think the cause of this issue due to Nintendo's official servers are shut down there must be a workaround to fix this issue

**Comment by SpYHero33** [comment]
The game version is 2.7.2 and the SmmSever I dowloaded and compiled is the lastest version.

**Comment by sofientouati** [comment]
Just redownload smm server, somehow the old one didn't work

**Comment by SpYHero33** [comment]
I downloaded smm server from mega network disk,debug.log has no problem , but also has the 106-0502 error
[Debug.log](https://github.com/SmmServer/SmmServer/files/6278515/Debug.log)

**Comment by SpYHero33** [comment]
I have solved this problem,I redownloaded the cemu in smm server and it can play the game successfully.
Thank you very much.
