### ISSUE TITLE
Cemu closing in title screen

### ISSUE THREAD

**Issue by RenanZX** [SmmServer/SmmServer#3]
I don't know what's happening, when i going hit 'start' and 'start cemu' in SMMServer, whenever i enter into the game, cemu simply close. I did a clean installation, i configured cemu correctly, i already installed the update patch, i follow step by step the tutorial, what it could be?, any suggestion? Thanks

**Comment by mrexodia** [comment]
Could you follow these instructions and send your DebugView logs? https://github.com/SmmServer/SmmServer/issues/2#issuecomment-548879357

**Comment by RenanZX** [comment]
How can i export the log files?

**Comment by mrexodia** [comment]
File -> Save

**Comment by RenanZX** [comment]
[DebugView.LOG](https://github.com/SmmServer/SmmServer/files/3800058/DebugView.LOG)

**Comment by mrexodia** [comment]
Very strange. You can try deleting `dbghelp.dll` and putting the following in `C:\Windows\system32\drivers\etc\hosts`:

```
127.0.0.1 account.nintendo.net
127.0.0.1 wup-ama.app.nintendo.net
```

**Comment by RenanZX** [comment]
where is this file `dbghelp.dll`?

**Comment by mrexodia** [comment]
Next to Cemu.exe

**Comment by RenanZX** [comment]
Don't works

**Comment by mrexodia** [comment]
Does the game run normally in Cemu without SmmServer?

**Comment by RenanZX** [comment]
Yes

**Comment by mrexodia** [comment]
Does the game run in SmmServer’s Cemu if you go to options and disable
offline functionality in the Cemu options?

**Comment by RenanZX** [comment]
Where is this option?

**Comment by mrexodia** [comment]
In the Cemu options.

**Comment by RenanZX** [comment]
Here say that Online Disabled

**Comment by mrexodia** [comment]
And does the game run?

**Comment by RenanZX** [comment]
i can't change this option

**Comment by RenanZX** [comment]
Yes the game runs normally

**Comment by RenanZX** [comment]
I put `dbghelp.dll` back and erase
`127.0.0.1 account.nintendo.net`

`127.0.0.1 wup-ama.app.nintendo.net`
from hosts file, and it's show me the option smmdb from online options of cemu. But it's no use, i have the same problem

**Comment by mrexodia** [comment]
Could you do a **clean** installation of SmmServer, the latest SMM update and record everything and upload it somewhere so I can take a look?

**Comment by RenanZX** [comment]
ok

**Comment by RenanZX** [comment]
i zip a video and upload it in git

[dw.zip](https://github.com/SmmServer/SmmServer/files/3802303/dw.zip)

**Comment by mrexodia** [comment]
Okay, so try the same but without changing the MLC path. You only need to install the SMM Update via `Cemu -> File -> Install game update or DLC` and everything should work.

If you cannot do this, copy the contents the `SmmServer\Cemu\mlc01` directory in your MLC path. **This can overwrite your own files, so it's better to use the previous solution**.

**Comment by RenanZX** [comment]
It's worked, thank you
