### ISSUE TITLE
python-3.7.5-embed-win32\lib\bs4\element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.

### ISSUE THREAD

**Issue by majdmfpro** [SmmServer/SmmServer#33]
i am having this problem, after i press start server i get this

[2022-02-11 22:04:47] INFO: [smmdb] nothing to do for Difficulty.Easy
[2022-02-11 22:04:47] INFO: [smmdb] fetching 16 Difficulty.Normal courses

this is logs
[Debug.log](https://github.com/SmmServer/SmmServer/files/8051075/Debug.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/8051077/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/8051078/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/8051079/Pretendo%2B%2B.log)
[Caddy.log](https://github.com/SmmServer/SmmServer/files/8051080/Caddy.log)

i tried to get a fresh copy from SmmServerFinal but it works good for half an hour then i get the same issue again

**Comment by majdmfpro** [comment]
anyone ?

**Comment by mrexodia** [comment]
Try the latest version, there was an update a few days ago. I think in February the smmdb domain was changed.

**Comment by majdmfpro** [comment]
thank you, i will give it a try 🌹

**Comment by majdmfpro** [comment]
thank you Mrexodia, after two days of trying, i can confirm that the problem is finally sloved.
