### ISSUE TITLE
ConnectionError: Couldn't connect to authentication server

### ISSUE THREAD

**Issue by hfiani** [SmmServer/SmmServer#34]
the smmserver was working fine, until suddenly it stopped working, i was unable to understand what it is. i also made an exception in the firewall for caddy
if you require any more information let me know.

[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/8261487/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/8261488/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/8261489/Pretendo%2B%2B.log)
[Caddy.log](https://github.com/SmmServer/SmmServer/files/8261490/Caddy.log)
[Debug.log](https://github.com/SmmServer/SmmServer/files/8261491/Debug.log)

**Comment by mrexodia** [comment]
Hm, for some reason it cannot connect to the authentication server. I’ll try and find some time to debug it, but maybe something is blocking UDP servers? Do you have any antivirus installed? And which Windows version are you on?

**Comment by hfiani** [comment]
i have windows defender of windows. i have 21H1 build 19043.1586 i will check the UDP thing. which processes should i allow? anything other than caddy?

**Comment by mrexodia** [comment]
Python, it is used to host the Prudp services over UDP. Generally they are hosted on localhost though, so a firewall rule shouldn’t be necessary.

**Comment by mrexodia** [comment]
From your SMM logs it doesn’t look like a prudp server is started (it should look similar to the friends service “blah started”)

**Comment by hfiani** [comment]
when i start the smmserver i get in NEX (friends)
`[2022-03-16 14:17:23] INFO: Starting PRUDP server at 127.0.0.1:60021:1
[2022-03-16 14:17:23] INFO: friends secure server 127.0.0.1:60021
[2022-03-16 14:17:23] INFO: Starting PRUDP server at 127.0.0.1:60000:1
[2022-03-16 14:17:23] INFO: friends auth server 127.0.0.1:60000
[2022-03-16 14:17:23] INFO: Press Ctrl+C to exit...
`

**Comment by hfiani** [comment]
anything else i should do or send to debug more?

**Comment by mrexodia** [comment]
The problem appears to be that the NEX (SMM) server isn’t starting properly, just weirdly enough without any errors…

**Comment by hfiani** [comment]
what process is the nex smm? maybe it needs also some firewall exceptions?

**Comment by mrexodia** [comment]
It’s also python, should be the same process as the friends server, just a different script

**Comment by hfiani** [comment]
nop. allowing pyhton did not work either

**Comment by mrexodia** [comment]
Can you provide a list of the software you have installed? I’ll give it a try when I have some more time, but last time I tested everything was working fine.

**Comment by hfiani** [comment]
i did not install anything for smmserver. otherwise if you are asking about my general software list, my pc is about 4 years old. it means there is a whole lot of software installed.

also a few days ago it was working fine, all i did was turn off my pc and turn it on the next day and it was no longer working

**Comment by mrexodia** [comment]
Yeah, the general software list is what I’m interested in. Particularly things that updated recently that could interfere.

**Comment by hfiani** [comment]
nothing updated recently. i update everything manually myself. if you can give me some infos maybe about the ports used and protocols, i can figure it out on my own. i am a programmer also

**Comment by mrexodia** [comment]
You can find the source code here: https://github.com/SmmServer/NintendoClients

**Comment by mrexodia** [comment]
Thanks for the info, will update the repo and do a new release!

**Comment by hfiani** [comment]
this worked for me thanks!
