### ISSUE TITLE
mouse dosent work

### ISSUE THREAD

**Issue by Delgadeth** [SmmServer/SmmServer#43]
Make sure to perform the following steps:

1. Open SmmServer
2. Click 'Start' to start the server
3. After a few seconds the 'Debug' button should become visible, press it
4. Wait for a while (~30 seconds)
5. Attach all `.log` files to the issue
[Debug.log](https://github.com/SmmServer/SmmServer/files/9333499/Debug.log)

Hi, when I lunch the game, the mouse dosent work.
If I use a newer version of Cemu, the mouse does it works, only with the version that comes with smmserver dosent work

**Comment by mrexodia** [comment]
It’s not related to SmmServer. Try replacing Cemu from the package with the latest one.
