### ISSUE TITLE
kicked out of 100 mario 106-0103 error how do i attach logs[2022-08-15 15:10:17] INFO: detected 100 mario [2022-08-15 15:10:18] INFO: DataStoreSmmServer.latest_course_search_object() [2022-08-15 15:10:18] WARNING: DataStoreSmmServer.latest_course_search_object not implemented [2022-08-15 15:10:18] INFO: RMC failed with error 0x80010002 (Core::NotImplemented)

### ISSUE THREAD

**Issue by nastycanasta21** [SmmServer/SmmServer#44]
Make sure to perform the following steps:

1. Open SmmServer
2. Click 'Start' to start the server
3. After a few seconds the 'Debug' button should become visible, press it
4. Wait for a while (~30 seconds)
5. Attach all `.log` files to the issue

**Comment by mrexodia** [comment]
Copy the log files next to SmmServer to GitHub

**Comment by nastycanasta21** [comment]
[log.txt](https://github.com/SmmServer/SmmServer/files/9339808/log.txt)

**Comment by nastycanasta21** [comment]
[debug files.txt](https://github.com/SmmServer/SmmServer/files/9354808/debug.files.txt)
Here are the logs from my last attempt at 100 mario. Did complete restore of computer and had the same issue.

**Comment by mrexodia** [comment]
You will need to wait until I have time to take a proper look. Are you using the latest update of Mario Maker?

**Comment by nastycanasta21** [comment]
yes

**Comment by mrexodia** [comment]
Did you make any significant progress in your save game or is this the vanilla game?

**Comment by nastycanasta21** [comment]
I had only completed the coursebot courses, and the 2015 world championship levels. I think there were three or four of them. All the online stuff like 100 mario could not do.

**Comment by nastycanasta21** [comment]
and its vanilla

**Comment by mrexodia** [comment]
Can you share your save file? It's in `Cemu\mlc01\usr\save` (you can zip the directory and attach it to the issue, but only include the `save` folder the other folders can contain copyrighted material).

Also it would help if you could make a screen recording (using OBS/ShareX) of the full process (starting SmmServer, starting the emulator, going to 100 mario etc).

**Comment by nastycanasta21** [comment]
[save.zip](https://github.com/SmmServer/SmmServer/files/9355087/save.zip)

https://user-images.githubusercontent.com/111297247/184997806-b250e7f7-8dd4-4ddb-ad81-382121a513a0.mp4

hopefully that is the save file you needed and hopefully the video is good enough if not I'll try again.

**Comment by mrexodia** [comment]
Hi, that's not the file I needed. Next to `SmmServer` there is a folder `Cemu` and in there you go to `mlc01 -> usr` and upload the `save` folder.

**Comment by nastycanasta21** [comment]
[save.zip](https://github.com/SmmServer/SmmServer/files/9355185/save.zip)

**Comment by mrexodia** [comment]
I tried, but everything is working fine. The error you were getting according to your logs was:

```
[2022-08-15 15:10:18] INFO: DataStoreSmmServer.latest_course_search_object()
[2022-08-15 15:10:18] WARNING: DataStoreSmmServer.latest_course_search_object not implemented
[2022-08-15 15:10:18] INFO: RMC failed with error 0x80010002 (Core::NotImplemented)
```

This happens when you go `Courses` and select `New Arrivals` and this is not supported (only 100 mario works). Once you get an error in the game you have to restart Cemu and reconnect for things to work again.

If you still have an issue, please record more of the screen and also make sure to include `NEX (SMM).log` (it's next to `SmmServer`). I did run into an issue with 100 mario once, but when I restarted the game everything worked fine...

**Comment by mrexodia** [comment]
I uploaded a new version you can try, it should be a bit more robust than the previous version and hopefully not have this error: https://mega.nz/file/j8JGhJaZ#3ro3HZEZTNHTnT_VNi_5PYQcQQJbKaP5e3-Zk4b6cz0

**Comment by nastycanasta21** [comment]
thank you I will try the new version and do everything else that you asked as well.

**Comment by nastycanasta21** [comment]
the new version works very well. There was one instance where I got an error message, but when I tried again it worked fine. There was also two times cemu closed itself down and I had to restart it. 100 mario does work I can play it with hardly any problems only the ones I already mentioned. Thank you again.

**Comment by mrexodia** [comment]
Could you upload the SMM logs again? I want to see if I can fix the issue.

**Comment by nastycanasta21** [comment]
[Caddy logs.txt](https://github.com/SmmServer/SmmServer/files/9378390/Caddy.logs.txt)
[debug files.txt](https://github.com/SmmServer/SmmServer/files/9378391/debug.files.txt)
[Pretendo++Logs.txt](https://github.com/SmmServer/SmmServer/files/9378392/Pretendo%2B%2BLogs.txt)
[SMM Logs.txt](https://github.com/SmmServer/SmmServer/files/9378394/SMM.Logs.txt)

**Comment by mrexodia** [comment]
I see one error:

```
[2022-08-18 20:31:37] INFO: DataStoreSmmServer.latest_course_search_object()
[2022-08-18 20:31:37] WARNING: DataStoreSmmServer.latest_course_search_object not implemented
[2022-08-18 20:31:37] INFO: RMC failed with error 0x80010002 (Core::NotImplemented)
```

This should be fixed in the latest version (v9). Thanks for helping me track down and fix these problems!
