### ISSUE TITLE
Err Eula Error Code:106-0502

### ISSUE THREAD

**Issue by Someone4321** [SmmServer/SmmServer#50]
In Cemu 1.15.3-7 (The one that comes by default) When I want to play online levels I get "_**ErrEula Error Code: 106-0502**_" which I think is a fairly common error and I need help to solve it. I tried and tried and I can't get it, any solution?

**Comment by Someone4321** [comment]
My log files:
[Caddy.log](https://github.com/SmmServer/SmmServer/files/15171511/Caddy.log)
[Debug.log](https://github.com/SmmServer/SmmServer/files/15171512/Debug.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/15171514/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/15171515/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/15171516/Pretendo%2B%2B.log)

**Comment by CoderReal** [comment]
if you have vmware installed run :
**taskkill /im vmware-hostd.exe /F** in cmd as admin

if that doesnt work try running : 
**NET stop HTTP** in cmd as admin

also run smmserver server as admin as it requires some ports to always be open to work

also if you are ever live streaming do NOT run that command as it will blue screen your computer (from experience lol)

**Comment by Someone4321** [comment]
Thank you so much!
:D

**Comment by Someone4321** [comment]
But how do I reverse the NET stop http command?

**Comment by mrexodia** [comment]
`net start http` but this is a non-critical part of Windows that is used for faster windows update across the LAN...

**Comment by Someone4321** [comment]
THANK YOU!!!!!!!!!!!!
