### ISSUE TITLE
Error-Code 106-1204

### ISSUE THREAD

**Issue by Kriper1111** [SmmServer/SmmServer#7]
I have tried fixes from other issues, they didn't work.
I have:
- replaced files in NindendoClients as suggested in #5 
- switched online option in Cemu on using "dummy" account
- disabled firewall
- unlocked files (windows said that "this file is recieved from another computer" in their properties)
- stopped the Windows IIS server that was running on background (but did not disabled it via the Control Panel)
- added nintendo addresses to hosts as suggested in #2 (but haven't rebooted yet)

Here are the logs:
[Caddy.log](https://github.com/SmmServer/SmmServer/files/4009311/Caddy.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/4009312/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/4009313/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/4009314/Pretendo%2B%2B.log)

And DebugView logs:
[cemu.LOG](https://github.com/SmmServer/SmmServer/files/4009315/cemu.LOG)

Unfortunately, GitHub refused to upload CurrPorts report

I am on Win7, x64 if that helps.

**Comment by Kriper1111** [comment]
Got it, do NOT delete the original "NintendoClients" entirely. At least leave the "www" folder. I'm sorry for being dumb.

**Comment by mrexodia** [comment]
Glad it was solves :slightly_smiling_face:

**Comment by wOwfmasf2** [comment]
> I have tried fixes from other issues, they didn't work.
> I have:
> 
> * replaced files in NindendoClients as suggested in #5
> * switched online option in Cemu on using "dummy" account
> * disabled firewall
> * unlocked files (windows said that "this file is recieved from another computer" in their properties)
> * stopped the Windows IIS server that was running on background (but did not disabled it via the Control Panel)
> * added nintendo addresses to hosts as suggested in #2 (but haven't rebooted yet)
> 
> Here are the logs:
> [Caddy.log](https://github.com/SmmServer/SmmServer/files/4009311/Caddy.log)
> [NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/4009312/NEX.Friends.log)
> [NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/4009313/NEX.SMM.log)
> [Pretendo++.log](https://github.com/SmmServer/SmmServer/files/4009314/Pretendo%2B%2B.log)
> 
> And DebugView logs:
> [cemu.LOG](https://github.com/SmmServer/SmmServer/files/4009315/cemu.LOG)
> 
> Unfortunately, GitHub refused to upload CurrPorts report
> 
> I am on Win7, x64 if that helps.

Help me how to do these idk anything please help me

**Comment by wOwfmasf2** [comment]
> Got it, do NOT delete the original "NintendoClients" entirely. At least leave the "www" folder. I'm sorry for being dumb.


HELP ME

**Comment by mrexodia** [comment]
I’ll take a look next week. Stop spamming the issue tracker or you’ll be
banned.
